-- this file is autogenerated by WowUp (app) at Mon Mar 31 2025 22:05:16 GMT-0400 (Eastern Daylight Time)
WOWUP_DATA = {}
WOWUP_DATA.icon = "Interface/AddOns/wowup_data_addon/ldbicon"
WOWUP_DATA.addonManagerName = "WowUp"
WOWUP_DATA.addonManagerColorRGB = {232/255,205/255,134/255}
WOWUP_DATA.addonManagerNameSlashCommand = "/wowup"
WOWUP_DATA.updateAddonsList = {
  ["ElvUI"] = {"v13.87", "13.87"},
}
